### ISSUE TITLE
Create a roadmap

### ISSUE THREAD

**Issue by carodew** [GSA/10x#5]
## it should include …
- [x] user promises, prioritized and/or in sequence 
- [x] break down the top priority user promise into features the team can work on (this can be broken down further in sprint planning/backlog grooming/breaking down the work meetings on an ongoing basis)
- [x] more loosely define some of the work that needs to be done on second priority user promise

## it's done when …
- [x] the team and stakeholders have agreed on the roadmap
- [ ] it's published on the GitHub repo in the Readme file.

**Comment by carodew** [comment]
Again, we can refer to the Modular PM curriculum in GSA's internal drive, slide decks about customer promises and roadmapping will be particularly useful here.

**Comment by carodew** [comment]
Road map!

![10x-website-story-map](https://user-images.githubusercontent.com/10144074/36212674-8fa90856-1172-11e8-8b3c-acc29c32a63e.png)
