### ISSUE TITLE
Make sure we have GSA's Office of Strategic Communications' (OSC) go-ahead before launch

### ISSUE THREAD

**Issue by willcahoe** [GSA/10x#93]
## Tasks
- [x] Reaching to André Francisco from 18F 
- [ ] Identify and connect with a POC from OSC
- [ ] Provide them with the link to the mostly done site
- [ ] When we approach them, describe how we meet GSA's website guidelines
- [ ] ask them if there's anything else we need to do

## it's done when …
- [ ] Someone with authority from GSA's Office of Strategic Communications says "yeah, go for it"

**Comment by carodew** [comment]
Have reached out to André and he's provided some good advice. 

Right now we're waiting until we have the content and visual design in a more finalized place before we reach out to OSC, but I've started a Google doc that runs down the pertinent GSA website guidelines and how we're meeting them so we can include that when we do reach out.
