### ISSUE TITLE
Plan for the site's post-launch maintenance and ownership

### ISSUE THREAD

**Issue by willcahoe** [GSA/10x#94]
## Tasks
- [ ] Develop a cadence for how often the site should be updated
- [ ] Identify roles and responsibilities 
- [ ] Estimate how much of a time commitment will be required to maintain the site
- [ ] Contingency planning: site is down, emergency content updates, who holds the keys, etc.

## it's done when …
- [ ] The person or people who will be responsible for the site's post-launch stewardship understand what is expected of them

**Comment by willcahoe** [comment]
Does anyone know if there is an TTS-specific "how to keep a website alive and thriving" playbook? If not, is there something similar from outside sources that someone can recommend?

**Comment by carodew** [comment]
I am not aware of any but it would be a great thing to ask some of our product folks and gather/share what comes out of it, although for something as simple as our site is, I'm guessing you've covered all the bases in your checklist above.

**Comment by willcahoe** [comment]
I'm going to pause this one until we can see the status of the site on Launch day and figure out what further work needs to happen

**Comment by RyanSibley** [comment]
@willcahoe When you have time, we should have a work session where we establish the work flow for updating content, etc.
